version: "2.4"

services:
  git:
    build:
      context: .
      dockerfile: docker/git.Dockerfile
    # prevent different users from clobbering each others images
    image: ${GIT_DOCKER_REPO}:git_${GIT_USERNAME}
    working_dir: ${GIT_CWD_DIR_DOCKER}
    environment:
      # Variables for just_entrypoint_functions
      - DOCKER_UID=${GIT_UID}
      - DOCKER_GIDS=${GIT_GIDS}
      - DOCKER_GROUP_NAMES=${GIT_GROUP_NAMES}
      - DOCKER_USERNAME=user
      - JUST_SETTINGS=/src/git.env
      - TZ
    volumes:
      # - type: ${GIT_SOURCE_DIR_TYPE}
      #   source: ${GIT_SOURCE_DIR}
      #   target: ${GIT_SOURCE_DIR_DOCKER}
      - type: ${GIT_CWD_DIR_TYPE}
        source: ${GIT_CWD_DIR}
        target: ${GIT_CWD_DIR_DOCKER}
      - type: bind
        source: ${GIT_CWD}/external/vsi_common
        target: /vsi
